services:
  nextjs:
    build:
      context: ./nikite-deploy/
      dockerfile: nikite-deploy/Dockerfile.dev
    container_name: nextjs
    ports:
      - "172.26.148.182:3000:3000"
    environment:
      NODE_ENV: production
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "172.26.148.182:80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
